title page

# Introduction

The following notebook contains the procedure and reasoning carried out for Data Wrangling and Cleaning. Where first the Data Wrangling was performed to homogenize the values of the attributes.

# 0. Import Libraries and Code

In [30]:
# Import libraries and functions

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

## 0.1 Code

In [49]:
def FiltersValuesBasedOnDataType(Dataset:pd.DataFrame,Attribute:str,Datatype) -> pd.Series:
    """
        Function to filter a dataframe based on datatype 
        of a feature or variable

        -- Dataset : pd.DataFrame :: Dataset where filtering is applied

        -- Attribute : str :: Feature to be filtered

        -- Datatype :: Data type to filter

        Return a series of boolean values where the 
        feature value's is equal with the data type
    """
    return Dataset[Attribute].apply(lambda value : type(value) is Datatype)

# 1. Dataset Loading and First Exploration

In [3]:
# Dataset loading from a xlsx file

CountriesInfo_Dataset = pd.read_excel("cia_paises.xlsx")

# Dataset dimension
CountriesInfo_Dataset.shape

(254, 14)

In [4]:
# Example of records

CountriesInfo_Dataset.head(5)

,Name,Continent,Area (km²),Population,GDP (USD),Unemployment Rate,Taxes (% of GDP),External Debt (USD),Exchange Rate (USD),Internet Users,Internet Users Percentage of Population,Airports,Roadways (km),Militar Expenditures (% of GDP)
0,Afghanistan,Asia,652230,37466414,2065,23.90,23.90,7.0,7.870,4717013.0,13.50,46.0,34903.0,1.2
1,Akrotiri,Middle East,123,18195,0,NaN,NaN,NaN,0.885,NaN,NaN,1.0,NaN,NaN
2,Albania,Europe,28748,3088385,13965,5.83,5.83,71.8,102.430,2196613.0,71.85,3.0,3945.0,1.3
3,Algeria,Africa,2381740,43576691,11511,11.70,11.70,27.5,131.085,24819531.0,59.58,149.0,104000.0,6.0
4,American Samoa,Oceania,224,46366,11200,29.80,29.80,12.2,1.000,17000.0,31.30,3.0,241.0,NaN

## 1.1 Reviewing Attributes

For each of the variables, the pertinent observations on the expected data types, data formatting and missing values are generated. This information will be used for the Data Wrangling and Preprocessing processes (Data Wrangling).

In [5]:
# Datatype by variable

CountriesInfo_Dataset.dtypes

Name                                        object
Continent                                   object
Area (km²)                                  object
Population                                  object
GDP (USD)                                    int64
Unemployment Rate                          float64
Taxes (% of GDP)                           float64
External Debt (USD)                        float64
Exchange Rate (USD)                        float64
Internet Users                             float64
Internet Users Percentage of Population    float64
Airports                                   float64
Roadways (km)                              float64
Militar Expenditures (% of GDP)            float64
dtype: object

In [59]:
# Splitting attribute into features and target

attribute_labels = CountriesInfo_Dataset.columns
Features = attribute_labels[:4].append(attribute_labels[5:])
Target = attribute_labels[4]

In [6]:
# Missing values by feature

CountriesInfo_Dataset.isnull().sum()

Name                                        0
Continent                                   0
Area (km²)                                  0
Population                                  0
GDP (USD)                                   0
Unemployment Rate                          34
Taxes (% of GDP)                           34
External Debt (USD)                        42
Exchange Rate (USD)                        15
Internet Users                             24
Internet Users Percentage of Population    24
Airports                                   16
Roadways (km)                              23
Militar Expenditures (% of GDP)            86
dtype: int64

In [48]:
# Name 

CountriesInfo_Dataset['Name'].describe()

count             254
unique            254
top       Afghanistan
freq                1
Name: Name, dtype: object

In [35]:
# Continent

CountriesInfo_Dataset[['Continent']].value_counts(dropna=False)

Continent
Africa                               55
Europe                               47
Central America and the Caribbean    33
Oceania                              28
Asia                                 22
Southeast Asia                       19
Middle East                          18
South America                        13
North America                         5
Antarctic Region                      4
Arctic Region                         4
Political Map of the World            2
AsiaEurope                            1
Antarctic RegionAfrica                1
European Union                        1
World                                 1
Name: count, dtype: int64

In [44]:
# Area
## Values without numerical or ambiguous formatting 

CountriesInfo_Dataset[['Area (km²)']][~FiltersValuesBasedOnDataType(CountriesInfo_Dataset,'Area (km²)',int)]

                Area (km²)
8                     14.2
45                   1.284
77         4,236,351 sq km
84                   total
164                  1.267
240                6959.41
250  510.072 million sq km

In [46]:
# Population
## Values without numerical or ambiguous formatting 

CountriesInfo_Dataset[['Population']][~FiltersValuesBasedOnDataType(CountriesInfo_Dataset,'Population',int)]

      Population
8             no
13            no
30   uninhabited
32            no
49   uninhabited
56            no
84            no
101  uninhabited
116           no
158  uninhabited
210           no
213           no
238       67.081
240           no
247           no

In [81]:
# Other numerical features

CountriesInfo_Dataset[Features[4:]].describe().T

,count,mean,std,min,25%,50%,75%,max
Unemployment Rate,220.0,1.022623e+01,1.036248e+01,0.1000,3.7525,6.900000e+00,1.190750e+01,7.700000e+01
Taxes (% of GDP),220.0,1.043386e+01,1.076974e+01,0.1000,3.7525,6.900000e+00,1.194750e+01,7.700000e+01
External Debt (USD),212.0,5.385755e+01,3.321727e+01,0.0000,33.2750,4.895000e+01,6.955000e+01,2.376000e+02
Exchange Rate (USD),239.0,8.810021e+01,2.173405e+02,0.3049,1.0000,3.668400e+00,4.503250e+01,2.013000e+03
Internet Users,230.0,3.550997e+07,2.685948e+08,54.0000,233831.2500,2.313282e+06,9.221140e+06,3.960000e+09
Internet Users Percentage of Population,230.0,5.670304e+01,2.863281e+01,1.3100,31.4000,6.011500e+01,8.082250e+01,1.000000e+02
Airports,238.0,3.488109e+02,2.855758e+03,1.0000,6.0000,2.900000e+01,9.600000e+01,4.182000e+04
Roadways (km),231.0,4.756744e+05,4.319549e+06,0.0000,2020.0000,1.990100e+04,8.534050e+04,6.428501e+07
Militar Expenditures (% of GDP),168.0,2.051667e+00,2.167059e+00,0.2000,1.0925,1.600000e+00,2.305000e+00,2.400000e+01

In [82]:
# Target 

CountriesInfo_Dataset[[Target]].describe()

           GDP (USD)
count     254.000000
mean    21355.062992
std     24244.833958
min         0.000000
25%      3490.750000
50%     12747.500000
75%     32891.250000
max    139100.000000

# 2. Data Wrangling

From the review of the attributes, the Area and Population attributes must first be formatted to be numeric values.

## 2.1 Area

Area values that are not integers, verify that: they are either floats (by performing a search based on the country name, they represent millions of kilometers) or they are strings, which contain the area.

In [29]:
CountriesInfo_Dataset[['Name','Area (km²)']][CountriesInfo_Dataset['Area (km²)'].apply(lambda value : not (type(value) is int))]

                                              Name             Area (km²)
8                                       Antarctica                   14.2
45                                            Chad                  1.284
77                                  European Union        4,236,351 sq km
84             French Southern and Antarctic Lands                  total
164                                          Niger                  1.267
240  United States Pacific Island Wildlife Refuges                6959.41
250                                          World  510.072 million sq km